name: DXTY EPG Update
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:  # 手动触发  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Delete epg/xml Folder
      run: |
        if [ -d "epg/xml/" ]; then
          rm -rf epg/xml/
          git rm -r --cached epg/xml/
          git commit -m "Delete epg/xml/ folder" || echo "No changes to commit"
          git push
        else
          echo "epg/xml/ directory not found, skipping deletion"
        fi
      env:
        PAT: ${{ secrets.GITHUBS_TOKEN }}
        
    - name: Update EPG Files
      run: |
        mkdir -p epg/xml/
        #rm -f epg/xml/e.xml && 
        wget https://epg.112114.xyz/pp.xml -O epg/xml/e.xml
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add epg/xml/e.xml
        git status
        git commit -m "EPG Automatic Update." || echo "No changes to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN  }}
    
    - name: Push changes
      run: git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN  }}
  
    - name: xml to json
      working-directory: epg
      run: |
        mkdir -p ./json
        pip3 install xmltodict
        python3 xml2json.py
   
    - name: Check files and git status
      run: |
        ls -l
        ls -l epg/xml
        ls -l epg/json
        git status

    - name: Commit and push epg changes
      run: |
        git add epg/*
        git status
        git commit -m "Update epg files" || echo "No changes to commit"
        git stash
        git pull origin main --rebase  # 确保拉取更新并解决冲突
        git push
      env:
        PAT: ${{ secrets.GITHUBS_TOKEN }} 
