name: DXTY EPG Update
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:  # 手动触发  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Git Identity
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # 你可以根据需要修改 PHP 版本
    
    - name: Delete epg/dxty Folder
      run: |
        if [ -d "epg/dxty/" ]; then
          rm -rf epg/dxty/
          git rm -r --cached epg/dxty/
          git commit -m "Delete epg/dxty/ folder" || echo "No changes to commit"
          git push
        else
          echo "epg/dxty/ directory not found, skipping deletion"
        fi
      env:
        PAT: ${{ secrets.GITHUBS_TOKEN }}
        
    - name: Update EPG Files
      run: |
        mkdir -p epg/dxty/
        php epg/dxty.php
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add epg/dxty/d.xml
        git add epg/xml/e.xml
        git status
        git commit -m "EPG Automatic Update." || echo "No changes to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN  }}
    
    - name: Push changes
      run: git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBS_TOKEN  }}

    - name: Check files and git status
      run: |
        ls -l
        ls -l epg/dxty
        ls -l epg/xml
        git status

    - name: Commit and push epg changes
      run: |
        git add epg/*
        git status
        git commit -m "Update epg files" || echo "No changes to commit"
        git stash
        git pull origin main --rebase  # 确保拉取更新并解决冲突
        git push
      env:
        PAT: ${{ secrets.GITHUBS_TOKEN }} 
